[global]
developmentMode = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base               = "dark"
primaryColor       = "#1155A4"
backgroundColor    = "#0F172A"
secondaryBackgroundColor = "#1F2937"
textColor          = "#E2E8F0"
font               = "sans serif"